site_name: system_design
site_url: https://system_design.com/

nav:
    - Home: index.md
    - Level1:
        - Pre Requisites: PreRequisites.md
        - Basic Terminologies: BasicTerminologies.md
        - Steps To Approach A Problem: StepsToApproachAProblem.md
        - System Design Interviews: SystemDesignInterviews.md
    - Level2:
        - Load Balancing: LoadBalancing.md
        - Caching: Caching.md
        - Data Partitioning: DataPartitioning.md
        - Indexes: Indexes.md
        - Proxies: Proxies.md
        - Redundancy and Replication: RedundancyReplication.md
        - SQL vs. NoSQL: SQLvsNoSQL.md
        - CAP Theorem: CAPTheorem.md
        - Consistent Hashing: ConsistentHashing.md
        - Long-Polling vs WebSockets vs Server-Sent Events: Events.md
    - Level3:
        - EASY:
            - Designing a URL Shortening service: DesigningURLShorteningService.md
            - Designing Pastebin: DesigningPastebin.md
        - MEDIUM:    
            - Designing Instagram: DesigningInstagram.md
            - Designing Dropbox: DesigningDropbox.md
            - Designing Facebook Messenger: DesigningFacebookMessenger.md
            - Designing Twitter: DesigningTwitter.md
            - Designing Twitter Search: DesigningTwitterSearch.md
            - Designing Youtube or Netflix: DesigningYoutubeorNetflix.md
            - Designing Typeahead Suggestion: DesigningTypeaheadSuggestion.md
            - Designing an API Rate Limiter: DesigningAPIRateLimiter.md
        - HARD:  
            - Designing a Web Crawler: DesigningWebCrawler.md
            - Designing Facebook’s Newsfeed : DesigningFacebookNewsfeed.md
            - Designing Yelp or Nearby Friends: DesigningYelporNearbyFriends.md
            - Designing Uber backend: DesigningUberBackend.md
            - Design Ticketmaster: DesignTicketmaster.md
        - Pratice Design Problems: PraticeDesignProblems.md
    - About: about.md


theme: readthedocs