site_name: My System Design
site_url: https://systemdesignbyjayaa.com/
nav:
    - Home: index.md
    #- System Design Basic: SystemDesignBasic.md
    - Key Characteristics of Distributed Systems: KeyCharDistributedSystem.md
    - Load Balancing: LoadBalancing.md
    - Caching: Caching.md
    - Data Partitioning: DataPartitioning.md
    - Indexes: Indexes.md
    - Proxies: Proxies.md
    - Redundancy and Replication: RedundancyReplication.md
    - SQL vs. NoSQL: SQLvsNoSQL.md
    - CAP Theorem: CAPTheorem.md
    - Consistent Hashing: ConsistentHashing.md
    - Long-Polling vs WebSockets vs Server-Sent Events: Events.md
    - System Design Interviews: SystemDesignInterviews.md
    - Question-Design a URL Shortening service: DesignURLShorteningService.md
    - Designing a URL Shortening service: DesigningURLShorteningService.md
    - Designing Pastebin: DesigningPastebin.md
    - Designing Instagram: DesigningInstagram.md
    - Designing Dropbox: DesigningDropbox.md
    - Designing Facebook Messenger: DesigningFacebookMessenger.md
    - Designing Twitter: DesigningTwitter.md
    - Designing Youtube or Netflix: DesigningYoutubeorNetflix.md
    - Designing Typeahead Suggestion: DesigningTypeaheadSuggestion.md
    - Designing an API Rate Limiter: DesigningAPIRateLimiter.md
    - Designing Twitter Search: DesigningTwitterSearch.md
    - Designing a Web Crawler: DesigningWebCrawler.md
    - Designing Facebook’s Newsfeed : DesigningFacebookNewsfeed.md
    - Designing Yelp or Nearby Friends: DesigningYelporNearbyFriends.md
    - Designing Uber backend: DesigningUberBackend.md
    - Design Ticketmaster: DesignTicketmaster.md
    - Pratice Design Problems: PraticeDesignProblems.md
    - About: about.md


theme: readthedocs

