site_name: My System Design
site_url: https://systemdesignbyjayaa.com/
nav:
    - Home: index.md
    - System Design Basic: SystemDesignBasic.md
    - Key Characteristics of Distributed Systems: KeyCharDistributedSystem.md
    - Load Balancing: LoadBalancing.md
    - Caching: Caching.md
    - Data Partitioning: DataPartitioning.md
    - Indexes: Indexes.md
    - Proxies: Proxies.md
    - Redundancy and Replication: RedundancyReplication.md
    - SQL vs. NoSQL: SQLvsNoSQL.md
    - CAP Theorem: CAPTheorem.md
    - Consistent Hashing: ConsistentHashing.md
    - Long-Polling vs WebSockets vs Server-Sent Events: Events.md
    - System Design Interviews: SystemDesignInterviews.md
    - Designing a URL Shortening service: DesigningURLShorteningService.md
    - Designing Pastebin: DesigningPastebin.md
    - About: about.md


theme: readthedocs

